# -*- coding: utf-8 -*-
"""Untitled98.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZAda5nI8Oe4e7pRkN0lyFtOTFNT9PR5n
"""

# Import necessary libraries
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the data
@st.cache
def load_data():
    return pd.read_csv('vd_revenue.csv')

# Preprocessing function
@st.cache
def preprocess_data(df):
    # Perform necessary preprocessing steps
    return df

# Function to plot revenue
def plot_revenue(filtered_data):
    plt.figure(figsize=(14, 7))
    sns.lineplot(data=filtered_data, x='rcpt_dt', y='revenue', estimator=sum, ci=None)
    plt.title('Revenue Over Time')
    plt.xlabel('Date')
    plt.ylabel('Revenue')
    plt.xticks(rotation=45)
    plt.tight_layout()
    st.pyplot()

# Main app function
def main():
    # Load and preprocess data
    df = load_data()
    df = preprocess_data(df)

    # Sidebar filters
    state = st.sidebar.selectbox('Select State', ['All'] + sorted(df['state_cd'].unique()))
    vehicle_category = st.sidebar.selectbox('Select Vehicle Category', ['All'] + sorted(df['vehicle_category'].unique()))
    payment_mode = st.sidebar.selectbox('Select Payment Mode', ['All'] + sorted(df['payment_mode'].unique()))

    # Filter data based on selections
    if state != 'All':
        df = df[df['state_cd'] == state]
    if vehicle_category != 'All':
        df = df[df['vehicle_category'] == vehicle_category]
    if payment_mode != 'All':
        df = df[df['payment_mode'] == payment_mode]

    # Plot
    plot_revenue(df)

# Run the app
if __name__ == '__main__':
    main()